### ISSUE TITLE
[feature]: Add Metrics exporter

### ISSUE THREAD

**Issue by destrex271** [destrex271/postgresexporter#1]

**Comment by rukins** [comment]
Hi @destrex271, thank you for your contribution! I am ready to implement metrics exporter, as it is needed for my company's project.
In addition, we are exploring the possibility of becoming a sponsor

**Comment by destrex271** [comment]
> Hi @destrex271, thank you for your contribution! I am ready to implement metrics exporter, as it is needed for my company's project.
> In addition, we are exploring the possibility of becoming a sponsor

Awesome. Thanks a lot for picking it up!
Would be great if we can get this merged in the official otel exporters.

I'll be happy to help out with pr reviews for this

**Comment by clarencebishop** [comment]
Hi, what is the status if the metrics exporter. I am needing this capability so that I can use PostgresSQL as my backend for my generated metrics.

**Comment by rukins** [comment]
Hi! It's implemented, just opened PR #2, please consider that it's still under development and may contain some bugs. we are testing it ourselves right now

**Comment by clarencebishop** [comment]
How do I access your  Postgress exporter under development in my local environment to play around with exporting metrics to a local Postgres database? What is the name of the Python package I need to include in my code? Sorry if these are simple answers but I am new to this. Thanks in advance for your help.

**Comment by destrex271** [comment]
> Hi! It's implemented, just opened PR [#2](https://github.com/destrex271/postgresexporter/pull/2), please consider that it's still under development and may contain some bugs. we are testing it ourselves right now. [@destrex271](https://github.com/destrex271) your review of the PR would be helpful

Suew, I'll get to it asap

**Comment by destrex271** [comment]
> How do I access your Postgress exporter under development in my local environment to play around with exporting metrics to a local Postgres database? What is the name of the Python package I need to include in my code? Sorry if these are simple answers but I am new to this. Thanks in advance for your help.

Hi, we don't have any python package for this exporter yet, for dev build purposes we follow the official OTEL guide to add new custom exporters using yaml config.
I'll update the documentation asap

**Comment by rukins** [comment]
> How do I access your Postgress exporter under development in my local environment to play around with exporting metrics to a local Postgres database? What is the name of the Python package I need to include in my code? Sorry if these are simple answers but I am new to this. Thanks in advance for your help.

@clarencebishop , if you mean how to create and expose metrics in your Python app, then you should use otel API and SDK (https://opentelemetry.io/docs/languages/python/).
But to use this postgres exporter (before it's merged into official repo), you can create your custom collector. Follow the step on https://opentelemetry.io/docs/collector/custom-collector/
Also here is example of configuration - https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/otelcontribcol

And

**Comment by rukins** [comment]
@clarencebishop , if you mean how to create and expose metrics in your Python app, then you should use otel API and SDK (https://opentelemetry.io/docs/languages/python/).

But to use this postgres exporter (before it's merged into official repo), you can create your custom collector. Follow the steps on https://opentelemetry.io/docs/collector/custom-collector/
Also here is example of configuration - https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/otelcontribcol

Your `builder-config.yaml` file should look similar to 

```yaml
dist:
  name: otellocalcol
  description: OpenTelemetry Collector Local for tests.
  version: 1.0.0
  output_path: ./cmd/otellocalcol

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.122.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.122.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.122.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.122.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.122.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.122.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.122.0
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.122.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.122.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.122.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.122.0

  - gomod: github.com/destrex271/postgresexporter v0.122.0
    path: "./exporter/postgresexporter" # if you have repo locally

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.28.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.28.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.28.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.28.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.28.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.122.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckv2extension v0.122.0

````

**Comment by destrex271** [comment]
> @clarencebishop , if you mean how to create and expose metrics in your Python app, then you should use otel API and SDK (https://opentelemetry.io/docs/languages/python/).
> 
> But to use this postgres exporter (before it's merged into official repo), you can create your custom collector. Follow the steps on https://opentelemetry.io/docs/collector/custom-collector/
> Also here is example of configuration - https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/otelcontribcol
> 
> Your `builder-config.yaml` file should look similar to 
> 
> ```yaml
> dist:
>   name: otellocalcol
>   description: OpenTelemetry Collector Local for tests.
>   version: 1.0.0
>   output_path: ./cmd/otellocalcol
> 
> receivers:
>   - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.122.0
>   - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.122.0
>   - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.122.0
>   - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.122.0
> 
> processors:
>   - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.122.0
>   - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.122.0
> 
> exporters:
>   - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.122.0
>   - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.122.0
>   - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.122.0
>   - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.122.0
>   - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.122.0
> 
>   - gomod: github.com/destrex271/postgresexporter v0.122.0
>     path: "./exporter/postgresexporter" # if you have repo locally
> 
> providers:
>   - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.28.0
>   - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.28.0
>   - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.28.0
>   - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.28.0
>   - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.28.0
> 
> extensions:
>   - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.122.0
>   - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckv2extension v0.122.0
> 
> ````
> 
> 

Thanks for adding it here! We should definitely move this to the readme of the project. I'll take care of that for now.

PS: I'll try to complete the review for this PR by Saturday and hopefully we can get it merged by Monday

**Comment by rukins** [comment]
@destrex271 thanks!

**Comment by clarencebishop** [comment]
Hi. I am getting the following error when I use ocb to build my custom collector with your postgres exporter:

exit status 1, error message: go: downloading github.com/destrex271/postgresexporter v0.122.0
go: github.com/destrex271/postgresexporter@v0.122.0: reading github.com/destrex271/postgresexporter/go.mod at revision v0.122.0: unknown revision v0.122.0

**Comment by rukins** [comment]
> Hi. I am getting the following error when I use ocb to build my custom collector with your postgres exporter:
> 
> exit status 1, error message: go: downloading github.com/destrex271/postgresexporter v0.122.0 go: github.com/destrex271/postgresexporter@v0.122.0: reading github.com/destrex271/postgresexporter/go.mod at revision v0.122.0: unknown revision v0.122.0

sorry, I was wrong, you should specify `main` instead of `v0.122.0`, fixed it.
But, before the metrics exporter merged into `main`, you can use it only by downloading the changes locally and setting `path`

**Comment by clarencebishop** [comment]
Hi. I have sucessfully built the postgres exporter but I am getting the following error when my application creates a metric that the collector receives:

go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1
	go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queue_sender.go:56
go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*disabledBatcher[...]).Consume
	go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/disabled_batcher.go:22
go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*asyncQueue[...]).Start.func1
	go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/async_queue.go:47
2025-04-18T10:45:21.860-0500	info	Metrics	{"resource metrics": 1, "metrics": 4, "data points": 6}
2025-04-18T10:45:21.878-0500	error	internal/queue_sender.go:56	Exporting failed. Dropping data.	{"error": "insert histogram metrics failed: ERROR: improper qualified name (too many dotted names): otel.http.server.duration (SQLSTATE 42601)", "dropped_items": 6}

**Comment by destrex271** [comment]
> Hi. I have sucessfully built the postgres exporter but I am getting the following error when my application creates a metric that the collector receives:
> 
> go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1
> 	go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queue_sender.go:56
> go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*disabledBatcher[...]).Consume
> 	go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/disabled_batcher.go:22
> go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*asyncQueue[...]).Start.func1
> 	go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/async_queue.go:47
> 2025-04-18T10:45:21.860-0500	info	Metrics	{"resource metrics": 1, "metrics": 4, "data points": 6}
> 2025-04-18T10:45:21.878-0500	error	internal/queue_sender.go:56	Exporting failed. Dropping data.	{"error": "insert histogram metrics failed: ERROR: improper qualified name (too many dotted names): otel.http.server.duration (SQLSTATE 42601)", "dropped_items": 6}
> 

Seems like a bug in metrics exported, are you using the metrics exporter branch that @rukins  is working on?

**Comment by rukins** [comment]
@clarencebishop please share the collector config you are using

**Comment by clarencebishop** [comment]
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  postgres:
  debug:

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters:
        - debug
        - postgres
    traces:
      receivers: [otlp]
      exporters:
        - debug
        - postgres
    metrics:
      receivers: [otlp]
      exporters:
        - debug
        - postgres

NOTE: I had to change postgresexporter to postgres for the exporter name

**Comment by clarencebishop** [comment]
Also, I am not seeing any logs or traces written to the otellogs and oteltraces table taht was created by the collector.

**Comment by rukins** [comment]
you haven't specified any database config, does it match defaults?

**Comment by clarencebishop** [comment]
I had to delete the database config information and use the defaults because of errors. It is using the default "otel" name for the database and schema. I can see that the collector is creating these objects.

**Comment by rukins** [comment]
do you have `_attributes_mappings` table created in your db?

**Comment by clarencebishop** [comment]
No, I did not see this table created in the otel database.

**Comment by rukins** [comment]
hmm, are you sure you are using the version from #2 ?

**Comment by clarencebishop** [comment]
I think so because I see all the newly added exporter_metrics.go file. Is there anyway to check that I am using the most current version of your work?

**Comment by clarencebishop** [comment]
I can see all of the metrics golang files in the internal directory.

**Comment by clarencebishop** [comment]
I can see the logs and traces in the respective tables. I was looking in the postgres database before instead of the otel database.

**Comment by clarencebishop** [comment]
Here is my builder-config yaml file:

dist:
  name: otellocalcol
  description: OpenTelemetry Collector Local for tests.
  version: 1.0.0
  output_path: ./cmd/otellocalcol

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.124.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.124.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.124.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.124.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.124.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.124.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.124.0
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.124.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.124.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.124.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.124.0

  - gomod: github.com/destrex271/postgresexporter v0.124.0
    path: "./exporter/postgresexporter" # if you have repo locally

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.28.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.28.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.28.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.28.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.28.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.124.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckv2extension v0.124.0

**Comment by rukins** [comment]
> Hi. I have sucessfully built the postgres exporter but I am getting the following error when my application creates a metric that the collector receives:
> 
> go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1 go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queue_sender.go:56 go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*disabledBatcher[...]).Consume go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/disabled_batcher.go:22 go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*asyncQueue[...]).Start.func1 go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/async_queue.go:47 2025-04-18T10:45:21.860-0500 info Metrics {"resource metrics": 1, "metrics": 4, "data points": 6} 2025-04-18T10:45:21.878-0500 error internal/queue_sender.go:56 Exporting failed. Dropping data. {"error": "insert histogram metrics failed: ERROR: improper qualified name (too many dotted names): otel.http.server.duration (SQLSTATE 42601)", "dropped_items": 6}

ah, I think I found the bug, yeah, will fix it now

**Comment by rukins** [comment]
> No, I did not see this table created in the otel database.

but, this table should have been created when you first run your collector

**Comment by clarencebishop** [comment]
The only objects created in the otel database are the following tables:
otellogs
oteltraces
oteltraces_trace_id_ts

And a materialized view:
oteltraces_trace_id_ts_mv

**Comment by rukins** [comment]
> > Hi. I have sucessfully built the postgres exporter but I am getting the following error when my application creates a metric that the collector receives:
> > go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1 go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queue_sender.go:56 go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*disabledBatcher[...]).Consume go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/disabled_batcher.go:22 go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*asyncQueue[...]).Start.func1 go.opentelemetry.io/collector/exporter@v0.124.0/exporterhelper/internal/queuebatch/async_queue.go:47 2025-04-18T10:45:21.860-0500 info Metrics {"resource metrics": 1, "metrics": 4, "data points": 6} 2025-04-18T10:45:21.878-0500 error internal/queue_sender.go:56 Exporting failed. Dropping data. {"error": "insert histogram metrics failed: ERROR: improper qualified name (too many dotted names): otel.http.server.duration (SQLSTATE 42601)", "dropped_items": 6}
> 
> ah, I think I found the bug, yeah, will fix it now

the bug is fixed, please pull new version and test it again

**Comment by rukins** [comment]
> The only objects created in the otel database are the following tables: otellogs oteltraces oteltraces_trace_id_ts
> 
> And a materialized view: oteltraces_trace_id_ts_mv

maybe that is because you disabled the metrics?🤔

**Comment by clarencebishop** [comment]
what is the git command I should use to get your latest updates? I want to make sure I am doing this correwctly.

**Comment by clarencebishop** [comment]
The metrics are no longer disabled and I still do not see the attributes table you mentioned.

**Comment by clarencebishop** [comment]
I have downloaded the code from the link above and rebuild the collector. It no longer generates the error that I was seeing before but I still do not see any metrics being collected. And I still do not see the _attributes_mappings table in the otel database.

**Comment by rukins** [comment]
the metrics is collected into `otel` schema by default, do you have it? this schema should have been auto created, as well

**Comment by clarencebishop** [comment]
I do not see an otel schema. The tables are being created in the public schema of the otel database.

**Comment by clarencebishop** [comment]
Do I need to manually create the otel schema?

**Comment by rukins** [comment]
> Do I need to manually create the otel schema?

no, it's created automatically

**Comment by clarencebishop** [comment]
When I use pgadmin to look atthe database objects. Under the otel database, the only schema showing is the public one. But when I try to manually create the otel schema, it says it already exist but still does not show it.

**Comment by rukins** [comment]
really weird :(
if it exists, maybe you just didn't reload the db?

**Comment by clarencebishop** [comment]
I have removed the otel database, manually recreated and re-ran the collector. I still do not see the otel schema under the Schema dropdown in pgadmin even though pgadmin tells me it exists when I tried to manually create it.

Where is the create_schema attribute set so I can check to make sure it is set to true?

**Comment by rukins** [comment]
your collector config should look similar to

```yaml
exporters:
        debug: {}
          # verbosity: detailed
        postgres:
          database:
            type: postgresql
            host: localhost
            port: 5432
            username: postgres
            password: postgres
            database: wabb
            schema: otel
          create_schema: true
```
